include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    prefer_const_constructors: true
    #prefer_single_quotes: true
    require_trailing_commas: true


formatter:
    trailing_commas: preserve